[arg("profile", pattern="dev|release|release-fast")]
build profile:
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    cmake --build build --target openscq30-gui

test:
    cmake -S . -B build -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release
    cmake --build build --target openscq30-gui-qml-test
    ctest --test-dir build --output-on-failure

install path:
    cmake --install build --prefix '{{ path }}'

uninstall path:
    rm -f '{{ path }}/bin/openscq30-gui'
    rm -f '{{ path }}/share/applications/com.oppzippy.OpenSCQ30.desktop'
    rm -f '{{ path }}/share/metainfo/com.oppzippy.OpenSCQ30.metainfo.xml'
    rm -f '{{ path }}/share/icons/hicolor/scalable/apps/com.oppzippy.OpenSCQ30.svg'
